
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obzriykbswkoikzvkjkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ienJpeWtic3drb2lrenZramtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjYwOTAsImV4cCI6MjA1ODI0MjA5MH0.gRiJnbVryGPCe0pLZd4J4xAP6LcgXI145IcEG3_GLz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
